# Generated by Django 4.1.5 on 2023-02-01 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangocourse', '0002_message_delete_distributionmessage_alter_client_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DistributionSettings',
        ),
        migrations.DeleteModel(
            name='DistributionTry',
        ),
    ]
