# Generated by Django 4.1.5 on 2023-02-05 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangocourse', '0003_delete_distributionsettings_delete_distributiontry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'клиент', 'verbose_name_plural': 'клиенты'},
        ),
        migrations.CreateModel(
            name='DistributionList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(null=True)),
                ('periodicity', models.CharField(choices=[('day', 'день'), ('week', 'неделя'), ('month', 'месяц')], default='day', max_length=10, verbose_name='Период')),
                ('status', models.CharField(choices=[('created', 'создано'), ('launched', 'запущено'), ('completed', 'завершено')], default='created', max_length=10, verbose_name='Статус')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangocourse.client')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangocourse.message')),
            ],
        ),
    ]
