# Generated by Django 4.1.6 on 2023-02-15 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangocourse', '0004_alter_client_options_distributionlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distributionlist',
            name='time',
        ),
    ]
