# Generated by Django 4.1.6 on 2023-02-15 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangocourse', '0005_remove_distributionlist_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributionlist',
            name='time',
            field=models.DateTimeField(null=True, verbose_name='Время рассылки'),
        ),
    ]
