# Generated by Django 4.1.6 on 2023-02-16 10:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangocourse', '0006_distributionlist_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributionlist',
            name='date',
            field=models.DateField(default=datetime.date(2023, 2, 16), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='distributionlist',
            name='time',
            field=models.TimeField(null=True, verbose_name='Время рассылки'),
        ),
    ]
